name: C/C++ CI

on:
  workflow_dispatch:

jobs:

  build-arm-none:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git gcc g++ gcc-multilib g++-multilib make libsdl2-dev zlib1g-dev
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build pd.elf
        run: make -f Makefile.port
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pd-arm
          path: build/
          retention-days: 0
      
